[tool.poetry]
name = "fast-admin"
version = "0.1.0"
description = ""
authors = ["liyatao <li_yatao@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
appboot = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

