"""
App Boot settings for fast_admin project.

Generated by 'appboot startproject' using App Boot.
"""

from pathlib import Path

from appboot.conf import DataBases

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent

PROJECT_NAME: str = 'fast_admin'

USE_TZ: bool = True

TIME_ZONE: str = 'Asia/Shanghai'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '117de29f8de5f96ed9e3234ea8949c5bebe13a2078f722eaedba9b79a50a2223'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = True

ALLOWED_HOSTS: list[str] = ['*']

ROOT_URLCONF: str = 'fast_admin.urls'

WSGI_APPLICATION = 'fast_admin.wsgi.application'

# Database
DATABASES: DataBases = DataBases(
    default=dict(url=f'sqlite+aiosqlite:///{BASE_DIR}/db.sqlite3', echo=DEBUG)
)